// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Book[]>}
 */
export function GetBooks() {
    return $Call.ByID(2971810543).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Version[]>}
 */
export function GetVersions() {
    return $Call.ByID(2463930162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Init() {
    return $Call.ByID(757639495);
}

/**
 * @param {string} queryStr
 * @param {string[]} selectedBooks
 * @param {string[]} selectedVersions
 * @returns {$CancellablePromise<$models.Verse[]>}
 */
export function Query(queryStr, selectedBooks, selectedVersions) {
    return $Call.ByID(675788687, queryStr, selectedBooks, selectedVersions).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} refStr
 * @returns {$CancellablePromise<$models.PassageRange>}
 */
export function ResolveRange(refStr) {
    return $Call.ByID(1117089036, refStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Book.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Version.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.Verse.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.PassageRange.createFrom;
