// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Book {
    /**
     * Creates a new Book instance.
     * @param {Partial<Book>} [$$source = {}] - The source object to create the Book.
     */
    constructor($$source = {}) {
        if (!("abbr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["abbr"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ord" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ord"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Book instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Book}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Book(/** @type {Partial<Book>} */($$parsedSource));
    }
}

export class Verse {
    /**
     * Creates a new Verse instance.
     * @param {Partial<Verse>} [$$source = {}] - The source object to create the Verse.
     */
    constructor($$source = {}) {
        if (!("book" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["book"] = "";
        }
        if (!("chapter" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chapter"] = 0;
        }
        if (!("verse" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["verse"] = 0;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Verse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Verse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Verse(/** @type {Partial<Verse>} */($$parsedSource));
    }
}

export class Version {
    /**
     * Creates a new Version instance.
     * @param {Partial<Version>} [$$source = {}] - The source object to create the Version.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lang"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Version}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Version(/** @type {Partial<Version>} */($$parsedSource));
    }
}
