// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(1482478474);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetDarkTheme() {
    return $Call.ByID(209903950);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetLightTheme() {
    return $Call.ByID(2858379956);
}
