// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LinkedNote {
    /**
     * Creates a new LinkedNote instance.
     * @param {Partial<LinkedNote>} [$$source = {}] - The source object to create the LinkedNote.
     */
    constructor($$source = {}) {
        if (!("noteId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["noteId"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("references" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["references"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkedNote instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LinkedNote}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField2_0($$parsedSource["references"]);
        }
        return new LinkedNote(/** @type {Partial<LinkedNote>} */($$parsedSource));
    }
}

export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("passages" in $$source)) {
            /**
             * @member
             * @type {Passage[]}
             */
            this["passages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("passages" in $$parsedSource) {
            $$parsedSource["passages"] = $$createField5_0($$parsedSource["passages"]);
        }
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}

export class NoteHeader {
    /**
     * Creates a new NoteHeader instance.
     * @param {Partial<NoteHeader>} [$$source = {}] - The source object to create the NoteHeader.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteHeader instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NoteHeader}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new NoteHeader(/** @type {Partial<NoteHeader>} */($$parsedSource));
    }
}

export class Passage {
    /**
     * Creates a new Passage instance.
     * @param {Partial<Passage>} [$$source = {}] - The source object to create the Passage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("reference" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reference"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Passage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Passage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Passage(/** @type {Partial<Passage>} */($$parsedSource));
    }
}

export class Tag {
    /**
     * Creates a new Tag instance.
     * @param {Partial<Tag>} [$$source = {}] - The source object to create the Tag.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag(/** @type {Partial<Tag>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Passage.createFrom;
const $$createType2 = $Create.Array($$createType1);
