// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.Tag>}
 */
export function CreateTag(name) {
    return $Call.ByID(1976438359, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id) {
    return $Call.ByID(239351074, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTag(id) {
    return $Call.ByID(2095896950, id);
}

/**
 * @param {string} ref
 * @returns {$CancellablePromise<$models.LinkedNote[]>}
 */
export function GetLinkedNotes(ref) {
    return $Call.ByID(2041018787, ref).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Note>}
 */
export function GetNote(id) {
    return $Call.ByID(1655260611, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Tag[]>}
 */
export function GetTags() {
    return $Call.ByID(811274038).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Init() {
    return $Call.ByID(1759092655);
}

/**
 * @param {string} noteID
 * @param {string} ref
 * @returns {$CancellablePromise<$models.Passage>}
 */
export function LinkPassage(noteID, ref) {
    return $Call.ByID(3676623459, noteID, ref).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.NoteHeader[]>}
 */
export function ListNotes() {
    return $Call.ByID(643541650).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.Note} note
 * @returns {$CancellablePromise<void>}
 */
export function SaveNote(note) {
    return $Call.ByID(2666709232, note);
}

/**
 * @param {string} passageID
 * @returns {$CancellablePromise<void>}
 */
export function UnlinkPassage(passageID) {
    return $Call.ByID(774301718, passageID);
}

// Private type creation functions
const $$createType0 = $models.Tag.createFrom;
const $$createType1 = $models.LinkedNote.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Note.createFrom;
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $models.Passage.createFrom;
const $$createType6 = $models.NoteHeader.createFrom;
const $$createType7 = $Create.Array($$createType6);
